### ISSUE TITLE
Get-Content returns GenericComplexObjects which can't be converted to strings?

### ISSUE THREAD

**Issue by adamkbmc** [jborean93/pypsrp#105]
I have a PowerShell script which is using the Get-Content cmdlet to retrieve a text file on a remote machine. When I invoke the script, the output includes the content as GenericComplexObjects ... is that right? Even if it is, you can't convert these objects to strings using str() like you can with most other things

I've also tried using Get-Content -Raw which is supposed to return the content as a single string (which is pretty much what I want) but I still get a single GenericComplexObject

I have found that the content is present in the GenericComplexObject in the property_sets attribute (as a list) - right now I am using this to get the data I want, but it feels wrong/fragile 

What is the right way to handle this?

Here is a script which illustrates my problem:

```
from pypsrp.wsman import WSMan
from pypsrp.powershell import PowerShell, RunspacePool
from pprint import pprint

wsman = WSMan(
    server   = 'host.acme.com',
    username = "user",
    password = "secret",
    auth     = "negotiate",
)

pool = RunspacePool(wsman)
pool.open()

ps = PowerShell(pool)
ps.add_script(r'Get-Content -Path C:\Windows\System32\drivers\etc\hosts')
output = ps.invoke()

pprint(output)
```

which gives me:

[<pypsrp.complex_objects.GenericComplexObject object at 0x7fc144453970>,
 <pypsrp.complex_objects.GenericComplexObject object at 0x7fc144453f40>,
 <pypsrp.complex_objects.GenericComplexObject object at 0x7fc144465be0>,
 <pypsrp.complex_objects.GenericComplexObject object at 0x7fc1444588e0>,
 <pypsrp.complex_objects.GenericComplexObject object at 0x7fc144465af0>,
 <pypsrp.complex_objects.GenericComplexObject object at 0x7fc144458f10>,
 <pypsrp.complex_objects.GenericComplexObject object at 0x7fc1444658e0>,
....
]

**Comment by jborean93** [comment]
This is unfortunately a use case that I poorly understood when I first built the serializer and I've never been happy with it. In this particular case `Get-Content` is returning a list of strings with extended properties. Normally a string is fine and appears as a normal `str` in Python but it's the extra extended properties that PS adds that causes the problem here. Here is what the raw data that is returned from a `Get-Content` call

```xml
<Obj RefId="0">
  <S>abc</S>
  <MS>
    <S N="PSPath">C:\\temp\\test.out</S>
    <S N="PSParentPath">C:\\temp</S>
    <S N="PSChildName">test.out</S>
    <Obj N="PSDrive" RefId="1">
      <TN RefId="0">
        <T>System.Management.Automation.PSDriveInfo</T>
        <T>System.Object</T>
      </TN>
      <ToString>C</ToString>
      <Props>
        <S N="CurrentLocation">Users\\vagrant-domain\\Documents</S>
        <S N="Name">C</S>
        <S N="Provider">Microsoft.PowerShell.Core\\FileSystem</S>
        <S N="Root">C:\\</S>
        <S N="Description">Windows 2019</S>
        <Nil N="MaximumSize"/>
        <Obj N="Credential" RefId="2">
          <TN RefId="1">
            <T>System.Management.Automation.PSCredential</T>
            <T>System.Object</T>
          </TN>
          <ToString>System.Management.Automation.PSCredential</ToString>
          <Props>
            <Nil N="UserName"/>
            <Nil N="Password"/>
          </Props>
        </Obj>
        <Nil N="DisplayRoot"/>
      </Props>
      <MS>
        <U64 N="Used">62905405440</U64>
        <U64 N="Free">22623789056</U64>
      </MS>
    </Obj>
    <Obj N="PSProvider" RefId="3">
      <TN RefId="2">
        <T>System.Management.Automation.ProviderInfo</T>
        <T>System.Object</T>
      </TN>
      <ToString>Microsoft.PowerShell.Core\\FileSystem</ToString>
      <Props>
        <S N="ImplementingType">Microsoft.PowerShell.Commands.FileSystemProvider</S>
        <S N="HelpFile">System.Management.Automation.dll-Help.xml</S>
        <S N="Name">FileSystem</S>
        <S N="PSSnapIn">Microsoft.PowerShell.Core</S>
        <S N="ModuleName">Microsoft.PowerShell.Core</S>
        <Nil N="Module"/>
        <S N="Description"/>
        <S N="Capabilities">Filter, ShouldProcess, Credentials</S>
        <S N="Home">C:\\Users\\vagrant-domain</S>
        <Obj N="Drives" RefId="4">
          <TN RefId="3">
            <T>System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSDriveInfo, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]</T>
            <T>System.Object</T>
          </TN>
          <LST>
            <Ref RefId="1"/>
          </LST>
        </Obj>
      </Props>
    </Obj>
    <I64 N="ReadCount">1</I64>
  </MS>
</Obj>
```

In this case the actual string value is the only element in `Obj` that isn't `<MS>`, <Prop>`, `<TN>`. At the time I just assumed this is how property sets were serialized and assumed that multiple elements could be returned which is why the `GenericComplexObject` contains a `property_sets` attribute that is a list. So getting the raw value from the property set is the right method to use and I cannot really change how it works today without breaking scripts that already rely on this behaviour.

A workaround would be to return the objects as pure strings and strip them of the extra properties that `Get-Content` is adding. You can do this by doing `(Get-Content -Path my_path).PSObject.BaseObject` to ensure the actual value(s) returned is a raw string.

In saying all this I understand the UX is very poor and unintuitive. I have some work going on in the background to try and make all this easier. Unfortunately it's still a WIP and will be a few months before I can include it in an actual release. The changes I've got going in the [asyncio](https://github.com/jborean93/pypsrp/tree/asyncio) branch implements a brand new serializer that makes this so much simpler and acts more like how PowerShell itself works. In this particular example the output appears as a string but still has those extra properties that PS smuggles back

```python
import asyncio
import psrp


async def main():
    wsman = psrp.AsyncWSManInfo('http://server2019.domain.test:5985/wsman')
    async with psrp.AsyncRunspacePool(wsman) as rp:
        ps = psrp.AsyncPowerShell(rp)
        ps.add_script(r'Get-Content C:\temp\test.out')

        out = await ps.invoke()

        # Contains a list of PSString's which is a subclass of str and acts the same
        print(out)

        # Can still access the extended properties that PowerShell returns
        print(out[0].ReadCount)

asyncio.run(main())

# Prints
# ['abc']
# 1
```

There will also be a synchronous API that acts in a very similar fashion to the existing `pypsrp` ones. Unfortunately I'm still in the middle of implementing a lot of this stuff so it's not really ready for prime time yet. I'm only really mentioning this to let you know that I do have a plan to solve this issue but it's slow progress.

**Comment by adamkbmc** [comment]
Thanks for confirming that I am (kind of) doing the right thing for now. The new asyncio approach looks interesting - let me know if you want help testing it :)

**Comment by jborean93** [comment]
The new `psrp` namespace which includes the new serializer and asyncio support has just been merged into `master`. I'm planning on releasing `1.0.0b1` soon to get these changes out in the wide to test but this will include the new changes I mentioned above.
