### ISSUE TITLE
Process is getting killed after it comes out of pool scope

### ISSUE THREAD

**Issue by mohit-madan** [jborean93/pypsrp#108]
Hi,
I am trying to run a process using the following code:
```
with wsman, RunspacePool(wsman) as pool:
     process = Powershell(pool).add_script("some command which starts a process")
     process.begin_invoke()
     process.poll_invoke()
     process.end_invoke()
```

the problem is that as soon as the code completes the process which has started in the remote shell say with pid =123
is killed. 
Is there any way to prevent the process from ending and let it keep running?

**Comment by jborean93** [comment]
Any process spawned in the RunspacePool is ended when that pool ends. To keep a process running you have 2 options

* Never close the pool
* Spawn a process outside the Windows job tied to the pool

The first option isn't really viable because the you need to open the pool manually and never close it keeping resources tied up on the server. The second option is simpler and you have 2 main methods to achieve this

* Run the process as a scheduled task
* Use `Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{...}`

It's up to you to decide what method to use and how you will monitor the progress/retrieve the output.
