### ISSUE TITLE
Long Running Command

### ISSUE THREAD

**Issue by mohitums** [jborean93/pypsrp#109]
Hi, 

I have a use for which I want to understand how the library functions and to see if there is any options available to support that. 

Currently we run a remote command(starting a process and getting output back) from a Linux Machine using pysprp onto a Windows machine, usually it takes about 30-40 seconds to complete.

Now in the new scenario the command will take longer (say about 24 hours) due to a long running process which is being executed in the remote machine(windows). So my question is, will the connection be terminated due to timeout? Also if there is a timeout do we have  a way to keep the connection active so the process can continue without any issues.   

I tried a small POC for 15-16 hours, it seems to be working fine without any issues but wanted to understand it better how it works or if there are any situation for which I need to account for. 

Thanks and appreciate any inputs or suggestions.

**Comment by jborean93** [comment]
It is definitely possible but I personally wouldn't recommend having a long running process to spawn the task as well as wait for the results. The issues you will inevitably have to solve

* Making sure the Python process stays running to keep the connection open
* Making sure the WinRM service isn't bounced or the long running process on the Windows side isn't killed for some reason
* Dealing with any network blips that might break the WinRM connection

If any of these things fail it will close the whole Runspace and kills any process' that it spawns, including your long running task.

This can somewhat be mitigated by creating a disconnected RunspacePool/Pipeline so you can stop the Python process and the remote PowerShell runspace continues to run but this then brings up more problems

* Disconnected runspaces definitely have a limited timeframe which is typically measured in hours and not days - default is 2 hours on my host
* If the process generates lots of output it will either hang until the data is received or it discards the output
* Only works for WSMan - not an issue for pypsrp because that is all that is offered

The advantages of the disconnected session is that you can spawn the process and have it run what you want, disconnect and have it continue in the background, reconnect and get the output that is buffered. The massive downside is the idle timeout (default of 2 hours) that will stop the Runspace once it is reached if a client hasn't reconnected back in that timeframe.

What I do recommend is to spawn a process in the background that is entirely disconnected from the remote PowerShell session and have that output the results to a file which you periodically poll. There are 2 main ways to spawn this type of process:

* Use `Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{...}`
* Create a scheduled task that you kick off immediately

The first option is simpler but the 2nd option gives you more information around historical run results and current status information. Once you've spawned the process you can then periodically poll the output file to see if it's finished, or even just keep running a process that respawns itself on a failure to get your results back.

**Comment by mohitums** [comment]
Hi,

Thanks a lot for detailed explanation, it clarifies quite a bit of things for me.
