### ISSUE TITLE
pypsrp TypeError: __init__() got an unexpected keyword argument 'status'

### ISSUE THREAD

**Issue by Mendez83** [jborean93/pypsrp#23]
Hi Jordan,
I am try to deploy a my app use pypsrp into a Debian machine and python 3.5 but i get some strange things if I try simple do:

>>> from pypsrp.client import Client
>>> client = Client("myserver", username="myuser", password="mypass")
>>> stdout, stderr, rc = client.execute_cmd("dir")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/client.py", line 195, in execute_cmd
    with WinRS(self.wsman) as shell:
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/shell.py", line 98, in __enter__
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/shell.py", line 204, in open
    option_set=options)
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/wsman.py", line 256, in create
    option_set, selector_set, timeout)
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/wsman.py", line 375, in invoke
    response = self.transport.send(xml)
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/wsman.py", line 701, in send
    self.session = self._build_session()
  File "/usr/local/lib/python3.5/dist-packages/pypsrp/wsman.py", line 799, in _build_session
    status_forcelist=(425, 429, 503),
TypeError: __init__() got an unexpected keyword argument 'status'

Do you know what could be?

**Comment by jborean93** [comment]
It is this particular line that's causing your problem https://github.com/jborean93/pypsrp/blob/master/pypsrp/wsman.py#L796. It seems like either your urllib3 install or Requests install is not meeting some minimum requirement (or something has broken in a newer release). Can you past the results of `pip list` here?

**Comment by danielNemeth19** [comment]
Hey Jordan,

First of all thanks very much for your work on this great library, it really looks promising for a task that I'm currently working on.

When trying your example scripts I run into the same issue as Mendez first - then I managed to get it work following your hint regarding minimum requirements of libraries.

In my original environment I had the following version required (only pasting the ones needed for pyprsrp):
asn1crypto: 0.23.0
cffi: 1.11.2
chardet: 2.3.0
cryptography: 2.1.3
idna: 2.6
ntlm-auth: 1.2.0
pip: 19.0.1
pycparser: 2.18
pypsrp: 0.3.0
requests: 2.9.1
setuptools: 40.6.2
six: 1.11.0
urllib3: 1.13.1
wheel: 0.24.0

Then after creating a brand new virtual env, the following versions got installed and the examples started to work:
asn1crypto: 0.24.0
cffi: 1.11.5
chardet: 3.0.4
cryptography: 2.5
idna: 2.8
ntlm-auth: 1.2.0
pip: 19.0.2
pycparser: 2.19
pypsrp: 0.3.0
requests: 2.21.0
setuptools: 40.8.0
six: 1.12.0
urllib3: 1.24.1
wheel: 0.33.0

I hope this helps to track down the issue!
Thank you

**Comment by jborean93** [comment]
Thanks @danielNemeth19, I'm sure the recent addition of the retry logic has now increased the minimum version required for requests. I need to do some digging to find out what version it was added and to see whether we should make it optional or raise the minimum requests version in the package.

**Comment by danielNemeth19** [comment]
Sure! I've actually quickly tried in my virtual env and can confirm that requests 2.14 is the minimum requirement to get it worked. Anything below that would raise this error.

**Comment by jborean93** [comment]
Fantastic, thanks for doing the hard work. I'll have a look and see whether it will be fine to raise the minimum version or just optionally set the retry block.

**Comment by jborean93** [comment]
@danielNemeth19 I've added some code with https://github.com/jborean93/pypsrp/commit/95fb032bab438590d88b0a571a9f84cbb12fe9f0 that will recreate the Retry handler without the `status` kwarg for older versions. I didn't want to raise the minimum version just yet so this still preserves some retry functionality for people who can't upgrade just yet.

I'll close this issue once I create a new release.

**Comment by danielNemeth19** [comment]
Thanks a lot Jordan! 

On an another note - I'm having some issues with getting done a task that I set out to myself.  I'll try to figure it out today because I'm sure it should work and it just a lack of knowledge / understanding on my part. But if I cannot resolve it would that be OK to reach out to you via email? Or would you prefer if I post any questions  as a comment under your "PowerShell Remoting on Python" blog post?
Thanks again!

**Comment by jborean93** [comment]
Probably post it here, it’s a lot easier to see and view comments as an issue than the blog post.

**Comment by danielNemeth19** [comment]
Sure, thank you! I've managed to construct the queries I needed so all good (so far) on that front. I have  just two general questions if you don't mind:

- I've seen that you're planning to support SSH transport too and you have an open branch for it. Is this plan sidelined for the time being, or is it something you expect to be done in the foreseeable future? By the way you mentioned in your blog that you are "still not fully sold on PowerShell Core" - I was wondering if you've changed your mind since then?

- My second query is about the windows server side - would you be able to point me to a doc that explains the recommended settings config wise that one needs to do on the windows machine for remote queries to run? I was following this guide https://4sysops.com/archives/powershell-remoting-between-windows-and-linux/ and also these ones: https://github.com/PowerShell/psl-omi-provider and https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enable-psremoting?view=powershell-6. My major worry is that most of the manuals I've seen (there were few others) are saying that I need to set basic auth and unnencrypted connections to true, trusted hosts to *,  while also mentioning that by the way these settings are not secure / recommended at all. I've read about using self-signed SSL certificates over HTTPS (https://4sysops.com/archives/powershell-remoting-over-https-with-a-self-signed-ssl-certificate/) but the setup seems to be quite daunting and what if I don't really have control over the remote machines? I guess my question is how safe is to use to use basic auth?

Sorry for the long-winded and off-topic questions.. I admittedly lack knowledge in this topic and any help or advise would be much appreciated!

Thank you

**Comment by jborean93** [comment]
@danielNemeth19 I've opened a new issue for each of your questions and will reply there.

**Comment by jborean93** [comment]
https://github.com/jborean93/pypsrp/releases/tag/v0.3.1 has been released today which should include this fix. Thanks for reporting the issue.
