### ISSUE TITLE
Starting Application on Windows using pypsrp

### ISSUE THREAD

**Issue by shekharpurwar** [jborean93/pypsrp#32]
I am trying to achieve basic task.
Task Description: Start an application on Windows machine from Linux machine.

If I use powershell command: Start-Job -ScriptBlock {<path_to_app>Application.exe}, locally on windows powershell, I am able to start Application.exe. But if I execute following script (remotely from Linux Machine) using pypsrp example code, this does not work. (I am not sure, if I am doing it wrongly, hence posting here).

```
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan("computer_name", username="xxxxxx", password="xxxxxx", ssl=False)

with RunspacePool(wsman) as pool:
    ps = PowerShell(pool)
    ps.add_script("Start-Job -ScriptBlock {<path_to_app>\Application.exe}")
    output = ps.invoke()

print("HAD ERRORS: %s" % ps.had_errors)
print("OUTPUT:\n%s" % "\n".join([str(s) for s in output]))
print("ERROR:\n%s" % "\n".join([str(s) for s in ps.streams.error]))
print("DEBUG:\n%s" % "\n".join([str(s) for s in ps.streams.debug]))
print("VERBOSE:\n%s" % "\n".join([str(s) for s in ps.streams.verbose]))
```

=======================================================================
Output:
```
HAD ERRORS: False
OUTPUT:
System.Management.Automation.PSRemotingJob
ERROR:

DEBUG:

VERBOSE:
```

Process finished with exit code 0

I tried PyWinRm also, I was able to start the application, but the control didn't return back to Python application, it just waited.

```
import winrm
s = winrm.Session('computer_name', auth=('xxxx', 'xxxx') , transport='kerberos')
res = s.run_cmd("notepad.exe")  #<-- Script execution stops here, waiting without returning control
```

**Comment by jborean93** [comment]
I don't think `Start-Job` is what you are looking for, that will start a brand new PowerShell process which then executes what is in the script block, if you are trying to do the same in psrp you should use [Start-Process](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-6) or the call operator (`&`) instead.

I'm unsure as to what you actually want to do with this application, are you wanting to;

1. Start the process and wait until it is complete
2. Start the process and continue executing more code while waiting for it to complete
3. Start the process and stop running scripts from pypsrp
4. Start the process and allow an interactive user logon to use it

1 is quite simple, just do

```
# More a free form script, you can run multiple commands quite easily but need to escape the args
ps.add_script("Start-Process -FileName '<path_to_app>\\Application.exe' -Wait

# Just run Start-Process without worrying about arg escaping but is a bit more verbose
ps.add_cmdlet("Start-Process").add_parameters({"FileName": "<path_to_app\\Application.exe", "Wait": True})
````

This will start the executable and wait until it exists similar to the pywinrm `run_cmd` example. There are other ways of doing this but this gives you the flexibility to do other things that `Start-Process` gives you.

2 is similar to 1 except you just omit the `-Wait` parameter. The only trouble is once the Runspace is exited the process will be killed by Windows. You would have to keep this open until you are ready for this.

3 is like 2 but it allows the process to continue running in the background without it being killed once the runspace has been closed. You would need to use WMI to get around this issue.

```
ps.add_script("Invoke-CimMethod -ClassName Win32_Process -Name Create -Arguments @{CommandLine='<path_to_app>\\Application.exe'}")
```

Be careful with this as you could potentially have orphaned processes that will continue to run unchecked if you don't clean up after yourself afterwards.

4 is not really possible, it can technically be done with a tool like `PsExec` but it would be brittle and not something I recommend you do.

> I tried PyWinRm also, I was able to start the application, but the control didn't return back to Python application, it just waited.

This is because `notepad.exe` had started but was never closed due to it being started in a non-interactive desktop. If you manually killed the process then pywinrm would have returned. This isn't an issue with pywinrm but just how WinRM works.

Really I just need some more info from you as to what you actually want to achieve.

**Comment by shekharpurwar** [comment]
Hi Jordan, thanks a lot for the reply and explanation. Basically, I have a Windows based machine (M1) that is used for testing Embedded Hardware
and it has few console applications, that I want to start from another machine which is Ubuntu (M2) based.
So I want to start application from M2 on M1 and pass some commandline arguments as well to initialize the application runnning on M1.
I am implementing a client application in python on M2 side to do these tasks. The client script should also check status of execution of application
and also stop application execution depending upon requirement (basically when tests are finished). 


Initially I used PyWinRM but soon found pypsrp. With PyWinRM, the client was not able to continue executing python script at M2 side as process needs to be
killed manually. I am trying figure out how that can be done, but not sure. But I was able to implement a threaded client, which just started (s.run_cmd("notepad.exe"))
commands in a separate thread and it worked. 

Do you think this implementation can be handled in a better way (without using threads) and/or if you have some other suggestions, that would be great !!!

Thank you

**Comment by jborean93** [comment]
Ok if you want to start an application in the background and exit the remote shell you would need to do the WMI/CIM method. This will be the same for all WinRM based libraries like pypsrp and pywinrm as when you close the shell it will kill and process spawned in that shell. Using the Win32_Process allows you to escape that context and the process will continue running in the background.

So for pypsrp you could do

```
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan("computer_name", username="xxxxxx", password="xxxxxx", ssl=False)

with RunspacePool(wsman) as pool:
    ps = PowerShell(pool)
    arguments = {
        "CommandLine": "notepad.exe"
    }
    parameters = {
        "ClassName": "Win32_Process",
        "Name": "Create",
        "Arguments": arguments,
    }
    ps.add_cmdlet("Invoke-CimMethod").add_parameters(parameters)
    output = ps.invoke()

    return_value = output[0].extended_properties['ReturnValue']
    process_id = output[0].extended_properties['ProcessId']
    print("Spawned PID: %d" % process_id)
```

This also shows you how to get the WMI ReturnValue that you can use to validate the WMI call, a non 0 value is an error. It will also return the PID of the newly spawned process so you can trace it. I went the `add_cmdlet` way as it gives you finer control over the parameter values but there is no reason why you can't do

```
ps.add_script("Invoke-CimMethod -ClassName Win32_Process -Name Create -Arguments @{ CommandLine = 'notepad.exe' }")
```
