### ISSUE TITLE
execute_ps doesn't work

### ISSUE THREAD

**Issue by pratz** [jborean93/pypsrp#45]
`execute_ps` doesn't work, however, `execute_cmd` works fine for the same cmd
<img width="1680" alt="Screen Shot 2019-08-21 at 2 39 59 pm" src="https://user-images.githubusercontent.com/925565/63403616-55915c80-c423-11e9-8267-1aeaf056d8e3.png">

**Comment by pratz** [comment]
Tried replacing `_` with `-` and all seems to work fine. Do you reckon underscore is at fault here?
<img width="1680" alt="Screen Shot 2019-08-21 at 3 07 48 pm" src="https://user-images.githubusercontent.com/925565/63404459-abb3cf00-c426-11e9-8872-1748a294ef22.png">

**Comment by pratz** [comment]
Works with Pywinrm but there's a error, if that helps
<img width="1680" alt="Screen Shot 2019-08-21 at 5 57 39 pm" src="https://user-images.githubusercontent.com/925565/63413559-4c14ee00-c43d-11e9-89ff-282cd03fc1cf.png">

**Comment by pratz** [comment]
Directory name `_X0031_` is converted to `1`
@jborean93 can you please take a look, I believe, somethings wrong with encoding or encryption.

**Comment by jborean93** [comment]
I had a play around and it looks like it's due to the string serialization rules in PSRP. The docs for [MS-PSRP](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-psrp/301404a9-232f-439c-8644-1a213675bfac) use the format `_x{d:4}_` as an escape sequence for a UTF-16 hex code so what pypsrp does is to convert certain chars to that format so Python can understand it. There's a special case where if something has an actual string that starts with `_x` it would be escaped as `_x005f_x`.

What's happening here is that the PSRP service is being case insensitive so it's seeing the string `_X0031_` and escaping it according to it's rules making the char `1`. Because the serializer in pypsrp is case sensitive is it only escaping `_x`. I was not aware that this was the case and will update the code at some point to fix this problem.

On a side note, because `$ErrorActionPreference = "Stop"` was not set in your script the tuple is returning `False` on the HadErrors field. If you check the errors stream in PSDataStreams you should see an error message in there.

**Comment by pratz** [comment]
Thanks mate, cheers 🍻
