### ISSUE TITLE
how to add a parameter like ScriptBlock

### ISSUE THREAD

**Issue by AndrewTsao** [jborean93/pypsrp#52]
Hi, I use `pypsrp`  to run command 'Start-Job'. this is my code,
```python
    with RunspacePool(wsman) as pool:
        # execute 'Get-Process | Select-Object Name'
        ps = PowerShell(pool)
        ps.add_cmdlet("Start-Job").add_parameter(
            "ScriptBlock", 'python.exe -c"import time;time.sleep(1000)"')
        ps.add_cmdlet("Out-String").add_parameter("Stream")
        output = ps.invoke()
        if ps.had_errors:
            log.error(str(ps.streams.error[0]))
```

```bat
ERROR:root:Cannot bind parameter 'ScriptBlock'. Cannot convert the "python.exe -c"import time;time.sleep(1000)"" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
```
How to bind a parameter `ScriptBlock` use `add_parameter`?

**Comment by jborean93** [comment]
The way that it is meant to be done is to use the `serialize()` method on the pool object and you specify the object meta that describes how to serialize it. It's easy for primitive types as you just need to set the tag based on the [MS-PSRP](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-psrp/c8c85974-ffd7-4455-84a8-e49016c20683) doc but complex types are a lot harder. I'm not too happy with how this actually turned out but for a [ScriptBlock](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-psrp/306af1be-6be5-4074-acc9-e29bd32f3206) it would look something like

```
...
from pypsrp.serializer import ObjectMeta
...

sbk = pool.serialize('python.exe -c "import time; time.sleep(1000)"', ObjectMeta('SBK'))
ps.add_cmdlet("Start-Job").add_parameter("ScriptBlock", sbk)
...
```

Even when you actually serialize the parameter value as a ScriptBlock I'm finding it's still failing with the same error. I can even replicate this with proper .NET library from Microsoft by trying to run

```
$ErrorActionPreference = 'Stop'

$conn_info = New-Object -TypeName System.Management.Automation.Runspaces.WSManConnectionInfo
$conn_info.ComputerName = 'dc01.domain.local'

$runspace = [RunspaceFactory]::CreateRunspace($host, $conn_info)
$runspace.Open()
try {
    $ps = [PowerShell]::Create()
    $ps.Runspace = $runspace

    $sb = [ScriptBlock]::Create('hostname.exe')
    $ps.AddCommand('Invoke-Command').AddParameter('Command', $sb) > $null

    $out = $ps.Invoke()
} finally {
    $runspace.Close()
}
```

The end result is always:

```
Exception calling "Invoke" with "0" argument(s): "Cannot bind parameter 'ScriptBlock'. Cannot convert the "..." value of type "System.String" to type "System.Management.Automation.ScriptBlock"."
At C:\temp\remote_sbk.ps1:30 char:5
+     $out = $ps.Invoke()
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RemoteException
```

I've doubled checked the code and even looked at the output that pypsrp is sending and the object is an actual ScriptBlock but something is happening on the server deserialization to convert that back to a string. I'm having a play around as this *should* work but doesn't and will hopefully figure out why.

As for a solution in the meantime, I would just add a script with what you want like so

```
ps.add_script('''$job_sb = [ScriptBlock]::Create($args[0])
Start-Job -ScriptBlock $job_sb
''').add_argument('python.exe -c "import time; time.sleep(1000)"')
ps.add_cmdlet('Out-String').add_parameter('Stream')
```

This works as you are passing in a string as the first argument and converting to a ScriptBlock on the server execution side.

**Comment by jborean93** [comment]
Having a look at https://github.com/PowerShell/PowerShell/blob/79e80a8e06ddf286b231dc853347059f6da37d39/src/System.Management.Automation/engine/serialization.cs#L4426 we can see the de serialization behaviour of the PSRP service which is to return the ScriptBlock body as a string if the `DeserializeScriptBlocks` flag isn't set. We can see that when the PSRP service creates the deserialization context at https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/remoting/common/fragmentor.cs#L984-L986, only `RemotingOptions` is set which does not include that flag. 

As a reference here are all the available `DeserializationOptions` flags that can be set https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/serialization.cs#L297. We can see that `RemotingOptions` does not include `DeserializeScriptBlocks` so ScriptBlocks are deserialized as just a string when it is received by the server.

Because the service converts a ScriptBlock to a string as soon as it is received we have no way of achieving what you need here with the plain `add_parameter()` function. You will have to use the `add_script()` method I showed you to achieve what you need. There is unfortunately nothing else I can do about that in this library so I am going to close this issue.
