### ISSUE TITLE
using %temp% in client.copy

### ISSUE THREAD

**Issue by jossef** [jborean93/pypsrp#59]
Copying files to target's `%TEMP%` is useful.
currently this
```
client.copy('/tmp/readme.txt', '%TEMP%\\readme.txt')
```
does not work, fails with error:

```
pypsrp.exceptions.WinRMError: Failed to copy file: Exception calling "Copy" with "3" argument(s): 
"Could not find a part of the path 'C:\Users\Administrator\Documents\%TEMP%\readme.txt'."
```

BTW awesome project.

**Comment by jborean93** [comment]
Unfortunately as you've found out pypsrp does not resolve the path based on env vars. It gets difficult because `%TEMP%` can be a valid folder name. What we could potentially do is add a kwarg like `expand_env_path` which defaults to `False`. Setting to `True` would then expand env vars like `%TEMP%` in the path and because it is opt-in a user should know if they want to expand it or not.

For now paths are relative to the default location of the shell. It may be possible to change the default location but typically it is `C:\Users\<user>\Documents` so you should be able to set `client.copy("/tmp/readme.txt', r'..\AppData\Local\Temp\readme.txt')`. The `copy()` function even returns the absolute path of the destination file so you can verify what it resolved to.

**Comment by jborean93** [comment]
This was implemented in https://github.com/jborean93/pypsrp/pull/68 and will be part of the next release. Both the `copy()` and `fetch()` functions have added the `expand_variables` kwarg that controls whether env vars are expanded or not.
