### ISSUE TITLE
Authentication using NTLM hash directly instead of plaintext password

### ISSUE THREAD

**Issue by mpgn** [jborean93/pypsrp#77]
Hello,

Is it possible to authenticate a user directly by passing his ntlm hash instead of the cleartext password ?

**Comment by mpgn** [comment]
Okay, sorry for the issue it's working well :)

**Comment by jborean93** [comment]
While not document I believe if you set `auth='ntlm'` and set the password to `LM_HASH:NT_HASH` where each hash is the 16 byte hex string for the LM and NT hash respectively of the password it should work. Also because the LM Hash is largely outdated and not actually used in modern versions of NTLM authentication so you can have that zero'd out. For example you could try the following:

```python
import base64
import hashlib

def ntlm_hash(password):
    b_nt_hash = hashlib.new('md4', password.encode('utf-16-le')).digest()
    nt_hash = base64.b16encode(b_nt_hash).decode().upper()

    return "00000000000000000000000000000000:%s" % nt_hash

nt_hash = ntlm_hash(u"password")
wsman = WSMan('server', username='username', password=nt_hash, auth='ntlm')
```

In the end you aren't really achieving anything here, this is the same logic that the underlying NTLM library uses and there's not even a guarantee it will support it as there are 3 versions that can be used depending on the underlying platform it runs on. NTLM will never send the passwor din cleartext, it does this same hashing for you, so instead of doing the step yourself you are better off just saving yourself the trouble and having the underlying library do it.

**Comment by mpgn** [comment]
I can confirm it's working using hash nt:lm like this `00000000000000000000000000000000:66E2BA62A0A8731F5DD6372DC26E0A18` as a password
